name: Check MarkdownFiles


on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-md-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Specify the Node.js version

    - name: Install markdown-link-check
      run: npm install -g markdown-link-check

    - name: Check for broken links
      run: |
        for file in $(find doc -name '*.md'); do
            echo "Checking links in $file"
            markdown-link-check "$file"
        done
            
          
